#ifndef JOYSTICKSMAPPING_H
#define JOYSTICKSMAPPING_H

enum HANWHA_BUTTON {
    LAYOUT_SEQ = 0,
    SEARCH = 1,
    FREEZE_ALARM = 2,
    CAMERA = 3,
    Number_1 = 4,
    NUMBER_6 = 5,
    RECORDER = 6,
    NUMBER_2 = 7,
    NUMBER_7 = 8,
    TILE_VM = 9,
    MENU_MOUSE = 10,
    NUMBER_4 = 11,
    NUMBER_9 = 12,
    MON_CON = 13,
    NUMBER_3 = 14,
    NUMBER_8 = 15,
    CAM = 16,
    NUMBER_5 = 17,
    NUMBER_ZERO = 18,
    SHIFT = 19,
    UP = 20,
    DOWN = 21,
    ESC_SETUP = 22,
    FAVORI_MACRO = 23,
    LEFT = 24,
    ENTER = 25,
    RIGHT = 26,
    FOCUS_NF = 27,
    L_TLOCK = 28,
    ZOOM = 29,
    R_TRACK = 30,
    IRIS_CO = 31,
    AF = 32,
    PTZ_TRACK = 33,
    PTZ_GROUP_TOUR = 34,
    PTZ_PRESET = 35,
    PTZ_MENU = 36,
    FAST_FORWARD = 37,
    STOP = 38,
    FAST_REWARD = 39,
    RECORD = 40,
    PAUSE_PLAY = 41,
    PTZ_RESET = 42,
};

#endif // JOYSTICKSMAPPING_H
